apiVersion: v1
kind: Secret
metadata:
  name: tiny-url-secrets
  namespace: tiny-url
type: Opaque
stringData:
  DB_PRIMARY_DSN: "postgres://urlshortener:CHANGE_THIS_PASSWORD@postgresql-primary:5432/urlshortener?sslmode=disable"
  DB_REPLICA1_DSN: "postgres://urlshortener:CHANGE_THIS_PASSWORD@postgresql-replica-1:5432/urlshortener?sslmode=disable"
  DB_REPLICA2_DSN: "postgres://urlshortener:CHANGE_THIS_PASSWORD@postgresql-replica-2:5432/urlshortener?sslmode=disable"
  DB_REPLICA3_DSN: "postgres://urlshortener:CHANGE_THIS_PASSWORD@postgresql-replica-3:5432/urlshortener?sslmode=disable"
  JWT_SECRET: "CHANGE_THIS_TO_A_SECURE_64_CHAR_SECRET_KEY_GENERATED_WITH_OPENSSL"
  REDIS_PASSWORD: ""
  CLICKHOUSE_PASSWORD: "clickhouse_password"
